repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'e2b496dc2bd8340c2524cb9a2d2a943cde1bb6df'  # frozen: v23.1.1
    hooks:
      - id: clang-format

  # Lint: YAML
  - repo: https://github.com/adrienverge/yamllint
    rev: cba56bcde1fdd01c1deb3f945e69764c291a6530  # frozen: v1.38.0
    hooks:
      - id: yamllint
        args: ["-d {extends: relaxed, rules: {line-length: disable}}", "-s"]
