repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'f4d7745e17a28aad7eed2f4874ca8d1568c11c4c'  # frozen: v22.1.8
    hooks:
      - id: clang-format

  # Lint: YAML
  - repo: https://github.com/adrienverge/yamllint
    rev: cba56bcde1fdd01c1deb3f945e69764c291a6530  # frozen: v1.38.0
    hooks:
      - id: yamllint
        args: ["-d {extends: relaxed, rules: {line-length: disable}}", "-s"]
