name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_ASAN=ON -DENABLE_UBSAN=ON ..
          cmake build .

      - name: Run executable
        run: ./build/main_tuple
